"""Remove is_public field from travel_logs

Revision ID: 061c51a212f7
Revises: 409c10404f2c
Create Date: 2025-07-10 22:58:53.209633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '061c51a212f7'
down_revision: Union[str, None] = '409c10404f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the is_public column from travel_logs table
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.drop_column('is_public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the is_public column
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
