"""Make travel_plan_id required in travel_logs

Revision ID: 468a4fd7ee0c
Revises: 061c51a212f7
Create Date: 2025-07-10 23:29:29.226087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '468a4fd7ee0c'
down_revision: Union[str, None] = '061c51a212f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make travel_plan_id NOT NULL in travel_logs table
    # Note: This assumes all existing travel_logs have a valid travel_plan_id
    # If there are NULL values, they need to be cleaned up first
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.alter_column('travel_plan_id',
                              existing_type=sa.String(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make travel_plan_id nullable again
    with op.batch_alter_table('travel_logs', schema=None) as batch_op:
        batch_op.alter_column('travel_plan_id',
                              existing_type=sa.String(),
                              nullable=True)
    # ### end Alembic commands ###
